source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, AllUserView, UserChangeView, UserPasswordChangeView, AddFriend, \
    DeleteFriend

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('add-friend/', AddFriend.as_view(), name='add_friend'),
    path('delete-friend/', DeleteFriend.as_view(), name='delete_friend'),

]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from accounts.views import AllUserView
from webapp.views import SendMessage, AllMessage

urlpatterns = [
    path('', AllUserView.as_view(), name='users'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('write-message/<int:id>/', SendMessage.as_view(), name='write_message'),
    path('messages', AllMessage.as_view(), name='all_messages')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user: User = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                      verbose_name='Пользователь')
    git_hub = models.URLField(null=True, blank=True, verbose_name='Git Hub')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    about_me = models.TextField(max_length=300, null=True, blank=True, verbose_name='О себе')
    friend = models.ManyToManyField(get_user_model(), blank=True, null=True, related_name='user', verbose_name='Друг')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.core.exceptions import ValidationError
from django.core.validators import ProhibitNullCharactersValidator

from accounts.models import Profile
from django.forms import inlineformset_factory


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(validators=[ProhibitNullCharactersValidator, ])
    last_name = forms.CharField(validators=[ProhibitNullCharactersValidator, ])

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        field_classes = {'username': UsernameField}

    # Автоматическое создание профилей
    def save(self, commit=True):
        user = super().save(commit=commit)
        Profile.objects.create(user=user)
        return user


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.http import JsonResponse
from django.views.generic.base import View

from .forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, ListView, UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator

from accounts.forms import MyUserCreationForm,  ProfileChangeForm
from django.views.generic import CreateView

from .models import Profile


class RegisterView(CreateView):
    model = User
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('users')
        return next_url


class UserDetailView( DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_project_by = 5
    paginate_project_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        user_profile = get_object_or_404(Profile, pk=user.pk)
        friends_list, page, is_paginated = self.paginate_comments(user_profile)
        context['friends_list'] = friends_list
        context['page_obj'] = page
        context['is_paginated'] = is_paginated
        context['friends'] = user_profile.friend.all()
        return context

    def paginate_comments(self, user):
        friend = user.friend.all()
        if friend.count() > 0:
            paginator = Paginator(friend, self.paginate_project_by, orphans=self.paginate_project_orphans)
            page = paginator.get_page(self.request.GET.get('page', 1))
            is_paginated = paginator.num_pages > 1
            return page.object_list, page, is_paginated
        else:
            return friend, None, False


class AllUserView(ListView):
    model = User
    template_name = 'users_view.html'
    context_object_name = 'users_list'
    paginate_by = 5
    paginate_orphans = 1

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            user = self.request.user
            profile = get_object_or_404(Profile, pk=user.pk)
            context['friends'] = profile.friend.all()
        except:
            pass
        return context

    def get_queryset(self):
        data = super().get_queryset()
        query = self.request.GET.get('search')
        print(query)
        if query:
            data = self.model.objects.filter(Q(first_name__icontains=query) | Q(last_name__icontains=query))
        return data


class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:login')


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class AddFriend(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        friend = get_user_model().objects.get(pk=data['id'])
        user = get_user_model().objects.get(pk=self.request.user.pk)
        profile = get_object_or_404(Profile, pk=user.pk)
        friends_profile = get_object_or_404(Profile, pk=friend.pk)
        if friend not in profile.friend.all():
            profile.friend.add(friend)
            friends_profile.friend.add(user)
            profile.save()
            friends_profile.save()
        else:
            print('уже есть')
        return reverse('users')


class DeleteFriend(View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        friend = get_user_model().objects.get(pk=data['id'])
        user = get_user_model().objects.get(pk=self.request.user.pk)
        profile = get_object_or_404(Profile, pk=user.pk)
        friends_profile = get_object_or_404(Profile, pk=friend.pk)
        if friend in profile.friend.all():
            profile.friend.remove(friend)
            friends_profile.friend.remove(user)
            profile.save()
            friends_profile.save()
        else:
            print('нет')
        return reverse('accounts:detail')

source/accounts/templates/user_change.html
{% extends 'people_base.html' %}

{% block title %}Редактировать пользователя{% endblock %}

{% block menu %}
        <a class="text-white text-center px-3" href="{% url "accounts:detail" user_obj.pk %}">Назад </a>
        <a class="text-white text-center px-3" href="{% url "accounts:password_change" user_obj.pk %}">Смена пароля</a>
{% endblock %}

{% block contant %}
    <h1 class="ml-5 pt-5">Поменять личные данные</h1>
    <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" class="btn btn-primary mb-2" value="Submit">
    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'people_base.html' %}

{% block title %}Регистрация{% endblock %}

{% block menu %}
{#    бонус #}
{% endblock %}

{% block contant %}
    <h1 class="mt-5 pt-5">Регистрация</h1>
    {% include 'partial/form.html' with form_method='post' button_text="Зарегистрироваться" %}
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'people_base.html' %}
{% load static %}
{% block title %}Пользователь{% endblock %}

{% block menu %}
    {% if request.user == user_obj %}
        <a class="text-white text-center px-3" href="{% url 'accounts:change' user_obj.pk %}">Редактирование личных данных</a>
        <a class="text-white text-center px-3" href="{% url "accounts:password_change" user_obj.pk %}">Смена пароля</a>
    {% endif %}
{% endblock %}

{% block contant %}
    <h1 class="ml-5 pt-5 pb-3">Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    <div class="row">
        <div class="col-4">
            {% if user_obj.profile.avatar %}
                <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
            {% else %}
                <img src="{% static "image/ava_.png" %}" alt="ava">
            {% endif %}
        </div>
        <div class="col-3">
            <p>Имя: {{ user_obj.first_name }} </p>
            <p>Фамилия: {{ user_obj.last_name }}</p>
            <p>Профиль на GitHub: <a href="{{ user_obj.profile.git_hub }}">{{ user_obj.profile.git_hub }}</a></p>
            <p>Почта: {{ user_obj.email }}</p>
            <p>О себе: {{ user_obj.profile.about_me }}</p>
        </div>
        <div class="col-5">
        <p>
        {% if request.user.is_authenticated %}
           {% if request.user != user_obj %}
                {% if request.user not in friends %}
                    <a href='{% url 'accounts:add_friend' %}' class="btn btn-primary my_button" onclick="AddFriend(event)"
                       id="{{ user_obj.pk }}">Добавить в друзья
                    </a>
                    {% else %}
                    <a href='{% url 'accounts:delete_friend' %}' class="btn btn-warning my_button" onclick="DeleteFriend(event)"
                        id="{{ user_obj.pk }}">Удалить из друзей
                    </a>
                {% endif %}
                <a href='{% url 'write_message' user_obj.pk %}' class="btn btn-success my_button">Отправить сообщение
                </a>
            {% endif %}
        {% endif %}
        </p>
        </div>
    </div>

    <h2 class="text-center clear">Друзья:</h2>
    {% include 'partial/friends_list.html'  with friends_list=friends_list%}
    <script type="application/javascript" src="{% static "js/add_friend.js" %}"></script>
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'people_base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block menu %}
    <a class="text-white text-center px-3" href="{% url "accounts:detail" user_obj.pk %}">Назад</a>
    <a class="text-white text-center px-3" href="{% url "accounts:change" user_obj.pk %}">Редактирование личных данных</a>
{% endblock %}

{% block contant %}
    <h1 class="ml-1 mt-5 pt-5">Смена пароля</h1>
    {% url "accounts:password_change" user_obj.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" %}
{% endblock %}

source/accounts/templates/users_view.html
{%  extends 'people_base.html' %}
{% load static %}
{% block title %}Users: {% endblock %}

{% block contant %}
        <hr>
    <div class="row">
        <div class=" col-lg-12 text-center">
            <h2 class="pt-4 pl-5"><b>All Users: </b></h2>
        </div>
    </div>
    <div class="row ml-5 pl-5">
        <div class=" col-lg-12 text-center">
            {% if is_paginated %}
                {% include 'partial/pagination.html' %}
            {% endif %}
        </div>
    </div>

    <hr>
    {% for user in users_list %}
        {% if user != request.user %}
            <div class="row mt-4">
                <div class="col col-lg-2 pl-5">
                    {% if user.profile.avatar %}
                        <img  src="{{ user.profile.avatar.url }}" width="125px" height="autho" alt="user picture">
                    {% else %}
                        <img src="{% static "image/ava_.png" %}" width="125px" height="autho" alt="ava">
                    {% endif %}
                </div>
                <div class="col col-lg-5">
                    <p>
                        Имя: <a href="{% url 'accounts:detail' user.pk %}">{{ user.first_name|default:user.username }}</a>,
                        Фамилия: <a href="{% url 'accounts:detail' user.pk %}">{{ user.last_name|default:user.username }}</a>
                    </p>
                </div>
                {% if request.user.is_authenticated  %}
                    <div class="col col-lg-5">
                        <p>
                            {% if user not in friends %}
                            <a href='{% url 'accounts:add_friend' %}' class="btn btn-primary my_button" onclick="AddFriend(event)"
                               id="{{ user.pk }}">Добавить в друзья
                            </a>
                            {% else %}
                            <a href='{% url 'accounts:delete_friend' %}' class="btn btn-warning my_button" onclick="DeleteFriend(event)"
                                id="{{ user.pk }}">Удалить из друзей
                            </a>
                            {% endif %}
                            <a href='{% url 'write_message' user.pk %}' class="btn btn-success my_button">Отправить сообщение
                            </a>
                        </p>
                    </div>
                {% endif %}
            </div>
            <hr class="mt-0">
        {% endif %}
    {% endfor %}
{#{% endif %}#}
    <script type="application/javascript" src="{% static "js/add_friend.js" %}"></script>
{% endblock %}