source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, AllUserView, UserChangeView, UserPasswordChangeView, AddFriend, \
    DeleteFriend

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('add-friend/', AddFriend.as_view(), name='add_friend'),
    path('delete-friend/', DeleteFriend.as_view(), name='delete_friend'),

]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from accounts.views import AllUserView
from webapp.views import SendMessage, AllMessage

urlpatterns = [
    path('', AllUserView.as_view(), name='users'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('write-message/<int:id>/', SendMessage.as_view(), name='write_message'),
    path('messages', AllMessage.as_view(), name='all_messages')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Message(models.Model):
    message = models.TextField(max_length=2000, verbose_name='Сообщение')
    author = models.ForeignKey(get_user_model(), related_name='author_message', default=1,
                               on_delete=models.SET_DEFAULT, verbose_name='Автор')
    recipient = models.ForeignKey(get_user_model(), related_name='recipient_message', default=1,
                                  on_delete=models.SET_DEFAULT, verbose_name='Получатель')
    sent_time = models.DateTimeField(auto_now_add=True,verbose_name='Время отправления')

    def __str__(self):
        return f'{self.author} - {self.message}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

source/webapp/forms.py
from django import forms

from webapp.models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']

source/webapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView

from webapp.forms import MessageForm
from webapp.models import Message


class SendMessage(LoginRequiredMixin, CreateView):
    model = Message
    template_name = 'massege/massege_create.html'
    form_class = MessageForm

    def form_valid(self, form):
        recipient_id = self.kwargs.get('id')
        recipient = get_user_model().objects.get(pk=recipient_id)
        message = form.save(commit=False)
        message.author = self.request.user
        message.recipient = recipient
        message.save()
        return redirect('all_messages')


class AllMessage(ListView):
    template_name = 'massege/all_messages.html'
    context_object_name = 'messages'
    model = Message
    paginate_by = 5
    paginate_orphans = 1
    ordering = ['-sent_time']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        messages = self.object_list
        messages_list, page, is_paginated = self.paginate_comments_send(messages)
        messages_list_recive, page_r, is_paginated_r = self.paginate_comments_recive(messages)
        context['messages_list'] = messages_list
        context['messages_list_recive'] = messages_list_recive
        context['page_obj'] = page
        context['is_paginated'] = is_paginated
        context['page_obj_r'] = page_r
        context['is_paginated_r'] = is_paginated_r
        return context

    def paginate_comments_send(self, messages):
        try:
            messages = messages.filter(author=self.request.user)
            if messages.count() > 0:
                paginator = Paginator(messages, self.paginate_by, orphans=self.paginate_orphans)
                page = paginator.get_page(self.request.GET.get('page', 1))
                is_paginated = paginator.num_pages > 1
                return page.object_list, page, is_paginated
            else:
                return messages, None, False
        except:
            return messages, None, False

    def paginate_comments_recive(self, messages):
        try:
            messages = messages.filter(recipient=self.request.user)
            if messages.count() > 0:
                paginator = Paginator(messages, self.paginate_by, orphans=self.paginate_orphans)
                page = paginator.get_page(self.request.GET.get('page', 1))
                is_paginated = paginator.num_pages > 1
                return page.object_list, page, is_paginated
            else:
                return messages, None, False
        except:
            return messages, None, False

source/webapp/templates/people_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}People{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand pl-3" href="/admin/">Admin</a>
            <a class="text-white text-center px-3" href="{% url 'users' %}">На главную</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if user.is_authenticated %}
                        <a class="text-white text-center px-3" href="{% url 'all_messages' %}">Сообщения</a>
                    {% block menu %}
                    {% endblock %}
                        <a class="text-white text-center px-3" href="{% url 'accounts:detail' request.user.pk %}">Hi {{ request.user.username }}</a>
                        <a class="text-white text-center px-3" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Logout</a>
                    {% else %}
                        <a class="text-white text-center px-3" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Login</a>
                        <a class="text-white text-center px-3"href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">Sing Up</a>
                {% endif %}
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                 <ul class="text-white text-center pt-2 px-3 mb-0">
                {% block search %}
                    <div class="search-form">
                        <form action="{% url 'users' %}" method="GET">
                            <input type="text" name="search">
                            <input type="submit" value="Найти">
                        </form>
                    </div>
                {% endblock %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-sm-5">
        {% block contant %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script type="application/javascript" src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>